from django.urls import path
from . import views
urlpatterns=[path('home/',views.c1,name='a'),
             path('',views.SignLogIn,name='SignLogIn'),
             path('signin/',views.signin,name='s1'),
             path('login/',views.mylogin,name='l1'),
             path('profile/',views.prof,name='profile'),
             path('save_prof_details/',views.save_prof_details,name='save_prof_details'),
             path('messenger/',views.messenger,name='messenger'),
             path('story/',views.Storylejana,name='story'),
             path('storyShow/',views.storyShow,name='storyShow'),
             path('sidenav/',views.sideNav,name='sideNav'),
             path('msgs/<str:sent_idS>',views.check_msgs,name='check_msgs'),
             path('searchres/<str:uname>',views.search,name='searchres'),
             path('search/',views.searchpage,name='search'),
             path('viewsearch/',views.viewsearch,name='viewsearch'),
             path('secuserprofile/',views.SecUserProfile,name='SecUserProfile'),
             path('shop/',views.Product,name='Product'),
             path('singlepro/<str:pname>/<int:pid>',views.product_details,name='product_details'),

             path('like/',views.like,name='like'),
             path('dislike/',views.dislike,name='dislike'),
             path('comment/',views.comment,name='comment'),
             path('jobs/',views.jobs,name='jobs'),
             path('hireform/',views.candidateform,name='candidateform'),
             path('Rform/',views.recruit_form,name='recruit_form'),
             path('Addcompany/',views.addcompany,name='Addcompany'),
             path('Addjob/',views.addjob,name='Addjob'),
             path('applyjob/',views.applyjob,name='applyjob'),
             path('myjobs/',views.myjobs,name='myjobs'),
             ]