# Generated by Django 5.0.3 on 2024-04-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='username',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='handleprofiledetail',
            name='name',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='handleprofiledetail',
            name='username',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
