# Generated by Django 5.0.3 on 2024-04-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_signin_username_alter_handleprofiledetail_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='storydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('txt_stry', models.TextField()),
                ('username', models.TextField()),
            ],
        ),
    ]
