# Generated by Django 5.0.3 on 2024-04-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_storydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='messegedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_by', models.CharField(max_length=20)),
                ('sent_to', models.CharField(max_length=20)),
                ('msg', models.TextField(max_length=100)),
                ('timing', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='storydata',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
