# Generated by Django 5.0.3 on 2024-04-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_messegedata_alter_storydata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messegedata',
            name='timing',
            field=models.DateTimeField(null=True),
        ),
    ]
