# Generated by Django 5.0.3 on 2024-04-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_messegedata_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='postdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('post', models.ImageField(upload_to='static/images')),
                ('caption', models.TextField(max_length=100)),
            ],
        ),
    ]
