# Generated by Django 5.0.3 on 2024-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_brand_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='handleprofiledetail',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
