# Generated by Django 5.0.3 on 2024-05-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_comments_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='likeId',
            new_name='postId',
        ),
    ]
