# Generated by Django 5.0.3 on 2024-05-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_username_likes_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
    ]
