# Generated by Django 5.0.3 on 2024-05-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commentId',
            new_name='postId',
        ),
    ]
