# Generated by Django 5.0.3 on 2024-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_commentid_comments_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentsVal',
            field=models.CharField(max_length=100),
        ),
    ]
