# Generated by Django 4.2.1 on 2024-05-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0017_alter_comments_commentsval'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('mobileno', models.IntegerField()),
                ('companylogo', models.ImageField(upload_to='static/images')),
                ('created_at', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('skillsrequired', models.CharField(max_length=100)),
                ('jobrequired', models.CharField(max_length=100)),
                ('educationrequired', models.CharField(max_length=100)),
                ('jobtype', models.CharField(choices=[('internship', 'internship'), ('fulltime', 'fulltime'), ('fresher', 'fresher')], max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('weeksdays', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('rolesandresponsibility', models.TextField(max_length=100)),
                ('created_at', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
