# Generated by Django 4.2.1 on 2024-05-08 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_company_created_at_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentDoneById',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='postId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likeDoneById',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='likesCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='postId',
            field=models.IntegerField(),
        ),
    ]
